edition = "2021"
newline_style = "Unix"
# comments
normalize_comments = true
wrap_comments = true
format_code_in_doc_comments = true
# imports
imports_granularity = "Crate"
group_imports = "StdExternalCrate"