FROM rust:alpine as builder
RUN apk add musl-dev

COPY . /tmp
WORKDIR /tmp

RUN cargo --version
RUN cargo build --example reviews --release

FROM alpine as base
COPY --from=builder /tmp/target/release/examples/reviews /usr/bin/reviews

ENTRYPOINT [ "reviews" ]
